### ISSUE TITLE
Add officer names to IA complaint description

### ISSUE THREAD

**Issue by nstory** [nstory/wokewindows#5]
The page `app/views/complaints/show.html.erb` already sets the `@layout_application_description` variable, but it doesn't list the officers in the complaint. Implement logic along these lines:

1. if there is one officer listed in the complaint, list their name in the description e.g. "Citizen Complaint received Aug 1, 2020 against John Smith"

2. if there are multiple officers listed in the complaint, say something like "against multiple officers"

3. if there are no officers listed in the complaint (this sometimes happens!) probably drop the "against xxx" part altogether

**Comment by jacoblurye** [comment]
Hi @nstory! Can I claim this issue?

**Comment by nstory** [comment]
Yes, go for it!
